baseURL: "https://jensadamczak.github.io/notes/"
languageCode: "en-us"
title: "Notes"
theme: "snippets"
taxonomies:
  book: books
  article: articles
  snippet: snippets
  videos: videos
  project: projects
menu:
  main:
    - identifier: "About"
      name: "About"
      url: "/about/"
    - identifier: "archive"
      name: "Archive"
      url: "/archive/"
markup:
  highlight:
    style: github 
  goldmark:
    renderer:
      unsafe: true
paginate: 10
